// =============================================================================
// STAGE 1: LAYOUT SHELL
// Generated by: ux-architect
// Purpose: Visual layout without functionality for human review
// Status: READY FOR REVIEW
// Pattern: Marketplace/App Store
// Entity: CommunityApp
// =============================================================================

import {
  Box,
  Container,
  Typography,
  Button,
  Chip,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Grid,
  Card,
  CardContent,
  CardActions,
  CardMedia,
  Avatar,
  Link,
  InputAdornment,
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import { PageHeaderComposable } from '@opengov/components-page-header';
import { capitalDesignTokens } from '@opengov/capital-mui-theme';
import { GABLayout } from '../components/GABLayout';
import { MOCK_COMMUNITY_APPS, CATEGORIES, type CommunityApp, type SortOption } from './mock-data';

// =============================================================================
// PROPS INTERFACE - Defines what will be wired up in Stage 2
// =============================================================================

interface CommunityPageLayoutProps {
  // State props
  selectedCategory?: string;
  searchQuery?: string;
  sortBy?: SortOption;
  apps?: CommunityApp[];
  featuredApps?: CommunityApp[];

  // Event handlers (no-ops in Stage 1)
  onCategoryChange?: (category: string) => void;
  onSearchChange?: (query: string) => void;
  onSortChange?: (sort: SortOption) => void;
  onAppAction?: (app: CommunityApp) => void;
  onViewAllApps?: () => void;
}

// =============================================================================
// LAYOUT COMPONENT - Pure JSX + Styling, No Business Logic
// =============================================================================

/**
 * Community Page Layout Component (STAGE 1)
 *
 * This is a pure layout component that renders the UI structure without
 * business logic. It receives all data and handlers as props.
 *
 * Sections:
 * - PageHeader: Title and actions (using PageHeaderComposable)
 * - Hero: Featured app showcase with large cards
 * - FilterBar: Category chips, search input, and sort dropdown
 * - NewAndUpdated: Grid of new/updated apps
 * - HelpLinks: Support and documentation links
 * - Footer: Legal links and copyright
 */
export function CommunityPageLayout({
  selectedCategory = 'All',
  searchQuery = '',
  sortBy = 'popular',
  apps = MOCK_COMMUNITY_APPS,
  featuredApps = MOCK_COMMUNITY_APPS.slice(0, 2),
  onCategoryChange = () => {},
  onSearchChange = () => {},
  onSortChange = () => {},
  onAppAction = () => {},
  onViewAllApps = () => {},
}: CommunityPageLayoutProps) {
  return (
    <GABLayout>
      <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
        {/* REQUIRED: PageHeaderComposable on every page */}
        <PageHeaderComposable maxContentWidth={capitalDesignTokens.foundations.layout.breakpoints.desktop.wide}>
          <PageHeaderComposable.Header>
            <PageHeaderComposable.Title>Community</PageHeaderComposable.Title>
          </PageHeaderComposable.Header>
        </PageHeaderComposable>

        {/* Main Content Area */}
        <Box sx={{ flex: 1, overflow: 'auto', bgcolor: 'background.default' }}>
          {/* Hero Section - Featured Apps */}
          <Box
            sx={{
              bgcolor: 'background.paper',
              borderBottom: 1,
              borderColor: 'divider',
              py: { xs: 3, md: 4 },
            }}
          >
            <Container maxWidth="lg">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 3 }}>
                <Typography
                  variant="h5"
                  sx={{
                    fontWeight: 600,
                    color: 'text.primary',
                  }}
                >
                  Featured
                </Typography>
                <Link
                  href="#"
                  onClick={(e) => {
                    e.preventDefault();
                    onViewAllApps();
                  }}
                  underline="hover"
                  sx={{
                    color: 'primary.main',
                    fontWeight: 500,
                    fontSize: '0.875rem',
                    cursor: 'pointer',
                  }}
                >
                  See All
                </Link>
              </Box>

              <Grid container spacing={3}>
                {featuredApps.map((app) => (
                  <Grid size={{ xs: 12, md: 6 }} key={app.id}>
                    <Card
                      sx={{
                        height: '100%',
                        display: 'flex',
                        flexDirection: 'column',
                        borderRadius: 2,
                        transition: 'all 0.2s ease-in-out',
                        '&:hover': {
                          transform: 'translateY(-2px)',
                          boxShadow: 3,
                        },
                      }}
                    >
                      <CardMedia
                        component="div"
                        sx={{
                          height: 200,
                          background: (theme) =>
                            `linear-gradient(135deg, ${theme.palette.primary.light}, ${theme.palette.primary.main})`,
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          fontSize: '4rem',
                        }}
                      >
                        {app.icon}
                      </CardMedia>
                      <CardContent sx={{ flexGrow: 1 }}>
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                          <Typography variant="h6" sx={{ fontWeight: 600, flex: 1 }}>
                            {app.title}
                          </Typography>
                          <Chip
                            label={app.category}
                            size="small"
                            variant="outlined"
                            sx={{ fontSize: '0.75rem' }}
                          />
                        </Box>
                        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                          {app.description}
                        </Typography>
                        {app.price && (
                          <Typography variant="body2" color="primary" sx={{ fontWeight: 600 }}>
                            {app.price}
                          </Typography>
                        )}
                      </CardContent>
                      <CardActions sx={{ p: 2, pt: 0 }}>
                        <Button
                          fullWidth
                          variant={app.installed ? 'outlined' : 'contained'}
                          size="large"
                          onClick={() => onAppAction(app)}
                        >
                          {app.installed ? 'Open' : 'Get'}
                        </Button>
                      </CardActions>
                    </Card>
                  </Grid>
                ))}
              </Grid>
            </Container>
          </Box>

          {/* Filter Bar Section */}
          <Box
            sx={{
              bgcolor: 'background.paper',
              borderBottom: 1,
              borderColor: 'divider',
              py: 2,
              position: 'sticky',
              top: 0,
              zIndex: 10,
            }}
          >
            <Container maxWidth="lg">
              {/* Category Filter Chips */}
              <Box sx={{ mb: 2, display: 'flex', alignItems: 'center', gap: 1, overflowX: 'auto', pb: 1 }}>
                <Typography
                  variant="overline"
                  sx={{
                    color: 'text.secondary',
                    fontWeight: 600,
                    letterSpacing: 0.5,
                    whiteSpace: 'nowrap',
                    mr: 1,
                  }}
                >
                  Categories
                </Typography>
                <Box sx={{ display: 'flex', gap: 1, flexWrap: 'nowrap' }}>
                  {CATEGORIES.map((category) => (
                    <Chip
                      key={category}
                      label={category}
                      onClick={() => onCategoryChange(category)}
                      color={selectedCategory === category ? 'primary' : 'default'}
                      variant={selectedCategory === category ? 'filled' : 'outlined'}
                      sx={{
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                        whiteSpace: 'nowrap',
                        '&:hover': {
                          bgcolor: selectedCategory === category ? 'primary.dark' : 'action.hover',
                        },
                      }}
                    />
                  ))}
                </Box>
              </Box>

              {/* Search and Sort Controls */}
              <Box sx={{ display: 'flex', gap: 2, flexDirection: { xs: 'column', sm: 'row' } }}>
                <TextField
                  fullWidth
                  placeholder="Search apps..."
                  value={searchQuery}
                  onChange={(e) => onSearchChange(e.target.value)}
                  size="small"
                  slotProps={{
                    input: {
                      startAdornment: (
                        <InputAdornment position="start">
                          <SearchIcon sx={{ color: 'text.secondary' }} />
                        </InputAdornment>
                      ),
                    },
                  }}
                  sx={{
                    bgcolor: 'background.default',
                  }}
                />
                <FormControl sx={{ minWidth: { xs: '100%', sm: 200 } }} size="small">
                  <InputLabel>Sort By</InputLabel>
                  <Select
                    value={sortBy}
                    label="Sort By"
                    onChange={(e) => onSortChange(e.target.value as SortOption)}
                    sx={{ bgcolor: 'background.default' }}
                  >
                    <MenuItem value="popular">Most Popular</MenuItem>
                    <MenuItem value="recent">Recently Added</MenuItem>
                    <MenuItem value="rating">Highest Rated</MenuItem>
                    <MenuItem value="name">Alphabetical</MenuItem>
                  </Select>
                </FormControl>
              </Box>
            </Container>
          </Box>

          {/* New and Updated Section */}
          <Container maxWidth="lg" sx={{ py: 4 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 3 }}>
              <Typography
                variant="h5"
                sx={{
                  fontWeight: 600,
                  color: 'text.primary',
                }}
              >
                New and Updated
              </Typography>
              <Link
                href="#"
                onClick={(e) => {
                  e.preventDefault();
                  onViewAllApps();
                }}
                underline="hover"
                sx={{
                  color: 'primary.main',
                  fontWeight: 500,
                  fontSize: '0.875rem',
                  cursor: 'pointer',
                }}
              >
                See All
              </Link>
            </Box>

            {/* App Grid */}
            <Grid container spacing={2}>
              {apps.map((app) => (
                <Grid size={{ xs: 12, sm: 6, md: 4, lg: 3 }} key={app.id}>
                  <Card
                    sx={{
                      height: '100%',
                      display: 'flex',
                      flexDirection: 'column',
                      borderRadius: 2,
                      transition: 'all 0.2s ease-in-out',
                      '&:hover': {
                        transform: 'translateY(-2px)',
                        boxShadow: 2,
                      },
                    }}
                  >
                    <CardContent sx={{ flexGrow: 1, pb: 1 }}>
                      {/* App Icon and Title */}
                      <Box sx={{ display: 'flex', gap: 1.5, mb: 1.5 }}>
                        <Avatar
                          sx={{
                            width: 48,
                            height: 48,
                            fontSize: '1.5rem',
                            bgcolor: app.iconBgColor || 'grey.100',
                            flexShrink: 0,
                          }}
                        >
                          {app.icon}
                        </Avatar>
                        <Box sx={{ flex: 1, minWidth: 0 }}>
                          <Typography
                            variant="subtitle2"
                            sx={{
                              fontWeight: 600,
                              mb: 0.5,
                              overflow: 'hidden',
                              textOverflow: 'ellipsis',
                              whiteSpace: 'nowrap',
                            }}
                          >
                            {app.title}
                          </Typography>
                          <Chip
                            label={app.category}
                            size="small"
                            variant="outlined"
                            sx={{ fontSize: '0.7rem', height: 20 }}
                          />
                        </Box>
                      </Box>

                      {/* Description */}
                      <Typography
                        variant="body2"
                        color="text.secondary"
                        sx={{
                          mb: 1,
                          display: '-webkit-box',
                          WebkitLineClamp: 2,
                          WebkitBoxOrient: 'vertical',
                          overflow: 'hidden',
                          lineHeight: 1.4,
                          minHeight: '2.8em',
                        }}
                      >
                        {app.description}
                      </Typography>

                      {/* Price or Free indicator */}
                      {app.price ? (
                        <Typography
                          variant="body2"
                          color="primary"
                          sx={{
                            fontWeight: 600,
                          }}
                        >
                          {app.price}
                        </Typography>
                      ) : (
                        <Typography
                          variant="body2"
                          color="text.secondary"
                          sx={{
                            fontWeight: 500,
                          }}
                        >
                          Free
                        </Typography>
                      )}
                    </CardContent>

                    <CardActions sx={{ p: 1.5, pt: 0 }}>
                      <Button
                        fullWidth
                        variant={app.installed ? 'outlined' : 'contained'}
                        size="small"
                        onClick={() => onAppAction(app)}
                      >
                        {app.installed ? 'Open' : 'Get'}
                      </Button>
                    </CardActions>
                  </Card>
                </Grid>
              ))}
            </Grid>
          </Container>

          {/* Help Links Section */}
          <Box
            sx={{
              bgcolor: 'background.paper',
              borderTop: 1,
              borderColor: 'divider',
              py: 3,
              mt: 4,
            }}
          >
            <Container maxWidth="lg">
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'center',
                  gap: 4,
                  flexWrap: 'wrap',
                }}
              >
                <Link
                  href="#"
                  underline="hover"
                  color="primary"
                  sx={{ fontWeight: 500, fontSize: '0.875rem' }}
                >
                  About App Purchases
                </Link>
                <Link
                  href="#"
                  underline="hover"
                  color="primary"
                  sx={{ fontWeight: 500, fontSize: '0.875rem' }}
                >
                  Report a Problem
                </Link>
              </Box>
            </Container>
          </Box>

          {/* Footer Section */}
          <Box
            sx={{
              bgcolor: 'background.default',
              borderTop: 1,
              borderColor: 'divider',
              py: 3,
            }}
          >
            <Container maxWidth="lg">
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'center',
                  gap: 2,
                  mb: 2,
                  flexWrap: 'wrap',
                }}
              >
                <Link href="#" variant="body2" color="text.secondary" underline="hover">
                  Terms of Use
                </Link>
                <Typography variant="body2" color="text.disabled">
                  •
                </Typography>
                <Link href="#" variant="body2" color="text.secondary" underline="hover">
                  Privacy Policy
                </Link>
                <Typography variant="body2" color="text.disabled">
                  •
                </Typography>
                <Link href="#" variant="body2" color="text.secondary" underline="hover">
                  Accessibility Statement
                </Link>
                <Typography variant="body2" color="text.disabled">
                  •
                </Typography>
                <Link href="#" variant="body2" color="text.secondary" underline="hover">
                  Sales and Refunds
                </Link>
                <Typography variant="body2" color="text.disabled">
                  •
                </Typography>
                <Link href="#" variant="body2" color="text.secondary" underline="hover">
                  Legal
                </Link>
              </Box>
              <Typography variant="body2" color="text.disabled" align="center">
                © 2025 OpenGov. All rights reserved.
              </Typography>
            </Container>
          </Box>
        </Box>
      </Box>
    </GABLayout>
  );
}

// =============================================================================
// STAGE 2: FULL COMPONENT WITH FUNCTIONALITY
// =============================================================================

// This section will be added by pattern-builder after human approval
// It will include:
// - State management (useState, useEffect)
// - Data fetching logic
// - Event handlers with real implementations
// - Filtering and sorting logic
// - Default export that wraps CommunityPageLayout component
