// =============================================================================
// MOCK DATA FOR COMMUNITY PAGE PREVIEW
// Generated by: ux-architect
// Purpose: Realistic sample data for Stage 1 layout review
// =============================================================================

export type SortOption = 'popular' | 'recent' | 'rating' | 'name';

export interface CommunityApp {
  id: string;
  title: string;
  category: string;
  description: string;
  icon: string;
  iconBgColor?: string;
  installed?: boolean;
  price?: string;
  rating?: number;
  downloads?: number;
  addedDate?: string;
}

export const CATEGORIES = [
  'All',
  'Productivity',
  'Automation',
  'Analytics',
  'Integration',
  'Utilities',
  'Communications',
  'Finance',
  'Planning',
  'Infrastructure',
  'Tourism',
];

export const MOCK_COMMUNITY_APPS: CommunityApp[] = [
  {
    id: '1',
    title: 'Loan Manager',
    category: 'Finance',
    description: 'Manage payments and collections with automated tracking and reporting',
    icon: '💰',
    iconBgColor: '#E8F5E9',
    installed: true,
    rating: 4.5,
    downloads: 1250,
    addedDate: '2024-11-15',
  },
  {
    id: '2',
    title: 'Social Media Publisher',
    category: 'Communications',
    description: 'Publish posts to all social platforms from a single dashboard',
    icon: '📱',
    iconBgColor: '#E3F2FD',
    price: '$1.99',
    rating: 4.8,
    downloads: 3200,
    addedDate: '2024-12-01',
  },
  {
    id: '3',
    title: 'Events Calendar',
    category: 'Planning',
    description: 'Create and schedule community events with automated reminders',
    icon: '📅',
    iconBgColor: '#FFF3E0',
    installed: true,
    rating: 4.3,
    downloads: 890,
    addedDate: '2024-10-20',
  },
  {
    id: '4',
    title: 'Utilities Manager',
    category: 'Infrastructure',
    description: 'Track outages and schedule maintenance for city utilities',
    icon: '⚡',
    iconBgColor: '#FFF9C4',
    price: '$2.99',
    rating: 4.6,
    downloads: 2100,
    addedDate: '2024-11-28',
  },
  {
    id: '5',
    title: 'Grant Manager',
    category: 'Finance',
    description: 'Manage grant requests and submissions with comprehensive tracking',
    icon: '🎯',
    iconBgColor: '#F3E5F5',
    price: '$1.99',
    rating: 4.4,
    downloads: 670,
    addedDate: '2024-09-15',
  },
  {
    id: '6',
    title: 'Spending Tracker',
    category: 'Finance',
    description: 'Track spending over time with detailed analytics and budget forecasting',
    icon: '💳',
    iconBgColor: '#FCE4EC',
    price: '$1.99',
    rating: 4.7,
    downloads: 1800,
    addedDate: '2024-12-05',
  },
  {
    id: '7',
    title: 'Project Manager',
    category: 'Planning',
    description: 'Track project progression with milestones, tasks, and resource allocation',
    icon: '📊',
    iconBgColor: '#E0F2F1',
    price: '$1.99',
    rating: 4.9,
    downloads: 4200,
    addedDate: '2024-11-01',
  },
  {
    id: '8',
    title: 'City Guides',
    category: 'Tourism',
    description: 'Create personalized guides for your area with maps and recommendations',
    icon: '🗺️',
    iconBgColor: '#E8EAF6',
    price: '$0.99',
    rating: 4.2,
    downloads: 520,
    addedDate: '2024-10-10',
  },
  {
    id: '9',
    title: 'Public Notice Manager',
    category: 'Communications',
    description: 'Post critical city updates and emergency notifications to residents',
    icon: '📢',
    iconBgColor: '#FFEBEE',
    installed: true,
    rating: 4.6,
    downloads: 1500,
    addedDate: '2024-11-20',
  },
  {
    id: '10',
    title: 'Workflow Automator',
    category: 'Automation',
    description: 'Automate repetitive tasks with visual workflow builder and templates',
    icon: '🔄',
    iconBgColor: '#E1F5FE',
    price: '$3.99',
    rating: 4.7,
    downloads: 2800,
    addedDate: '2024-12-10',
  },
  {
    id: '11',
    title: 'Budget Analytics',
    category: 'Analytics',
    description: 'Visualize budget allocation and spending patterns with interactive charts',
    icon: '📈',
    iconBgColor: '#F1F8E9',
    price: '$2.49',
    rating: 4.5,
    downloads: 1600,
    addedDate: '2024-11-25',
  },
  {
    id: '12',
    title: 'Document Sync',
    category: 'Integration',
    description: 'Sync documents across cloud storage providers with automatic backup',
    icon: '☁️',
    iconBgColor: '#FFF8E1',
    installed: true,
    rating: 4.8,
    downloads: 3500,
    addedDate: '2024-12-08',
  },
];
